//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaundraMateWebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LoundraMateDbEntities1 : DbContext
    {
        public LoundraMateDbEntities1()
            : base("name=LoundraMateDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Address> Addresses { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<WashinMachine> WashinMachines { get; set; }
        public DbSet<Store> Stores { get; set; }
        public DbSet<OrderTable> OrderTables { get; set; }
        public DbSet<Admin> Admins { get; set; }
        public DbSet<DeviceCode> DeviceCodes { get; set; }
    }
}
