//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaundraMateWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTable
    {
        public int Id { get; set; }
        public Nullable<int> CustId { get; set; }
        public string OrderType { get; set; }
        public Nullable<int> CustAddressId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string OrderStaus { get; set; }
        public Nullable<System.TimeSpan> PickupTime { get; set; }
        public Nullable<System.TimeSpan> DeliveryTime { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<decimal> OrderCost { get; set; }
        public Nullable<decimal> OrderWt { get; set; }
        public string PaymentMode { get; set; }
        public string MachineCode { get; set; }
        public string OrderDesc { get; set; }
    }
}
